//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autofin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_clientes
    {
        public t_clientes()
        {
            this.t_facturas = new HashSet<t_facturas>();
        }
    
        public int idCliente { get; set; }
        public string Nombre { get; set; }
        public string Domicilio { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<t_facturas> t_facturas { get; set; }
    }
}
