//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autofin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_facturas
    {
        public t_facturas()
        {
            this.t_detalleFactura = new HashSet<t_detalleFactura>();
        }
    
        public int idFactura { get; set; }
        public string NumeroFactura { get; set; }
        public Nullable<System.DateTime> FechaHora { get; set; }
        public Nullable<int> idCliente { get; set; }
    
        public virtual t_clientes t_clientes { get; set; }
        public virtual ICollection<t_detalleFactura> t_detalleFactura { get; set; }
    }
}
