//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace autofin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_productos
    {
        public t_productos()
        {
            this.t_detalleFactura = new HashSet<t_detalleFactura>();
        }
    
        public int idProducto { get; set; }
        public string Nombre { get; set; }
        public string Marca { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
    
        public virtual ICollection<t_detalleFactura> t_detalleFactura { get; set; }
    }
}
